modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
    modId="arcticpoi"
    version="1.0.0"
    displayName="Arctic Poi"
    authors="Lumine04"
    description='''First test of arctic structures for my modpack'''

[[dependencies.arcticpoi]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.arcticpoi]]
    modId="minecraft"
    mandatory=true
    versionRange="1.20.1"
    ordering="NONE"
    side="BOTH"

